server:
  port: 8000


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/smartconstruction?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Africa/Nairobi
#    username: root
#    password: password
#
#  jpa:
#
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Africa/Nairobi
#        format_sql: true


